title: Suppressed Images
description: >
  A story about Heather Dewey-Hagborg and Chelsea Manning 
url: "https://suppressedimages.github.io"
baseurl: "/"
paginate:	2 # The number of posts to show per page on your homepage
name: "Heather Dewey-Hagborg"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
